# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoTogether (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoTogether (iOS)
  pod 'Objective-LevelDB'
end

target 'VideoTogether (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoTogether (macOS)
  pod 'Objective-LevelDB'
end

target 'VideoTogether Extension (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoTogether Extension (iOS)
  pod 'Objective-LevelDB'
end

target 'VideoTogether Extension (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoTogether Extension (macOS)
  pod 'Objective-LevelDB'
end
