name: 提个建议
description: 给VideoTogether提个建议
title: "[建议] "

body:
  - type: markdown
    attributes:
      value: 这仅用于请求一个新特性
  - type: textarea
    id: feature-request
    attributes:
      label: 描述功能请求
      description: 告诉我们你想要什么，以及为什么要在VideoTogether中添加它
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 描述你考虑过的备选方案
  - type: checkboxes
    id: area
    attributes:
      label: 请确认此建议所影响的内容
      options:
        - label: "文档"
        - label: "安装"
        - label: "可扩展性"
        - label: "安全"
        - label: "用户体验"
        - label: "测试和发布"
        - label: "新的扩展"
        - label: "其他"